### ISSUE TITLE
enhance configuration options

### ISSUE THREAD

**Issue by McFoggy** [jgitver/gradle-jgitver-plugin#7]
support configurations options introduced in jgitver version > 0.2.0

**Comment by yo1-markenstein** [comment]
Thanks for this plugin. I am planning to use this in my projects.
Vote +1 for this issue ;-)
I need to set different `findTagVersionPattern` in my use cases.

**Comment by McFoggy** [comment]
@yo1-markenstein can you please open another issue, this one is closed. Also please describe more precisely what you want to achieve.

**Comment by McFoggy** [comment]
oups sorry, this one is not closed ;-)

**Comment by yo1-markenstein** [comment]
What I need is to be able to use a different pattern to select version tags (e.g. allowing pattern like `r1.1.0` for releases, not only `v1.1.0` or `1.1.0`)
As far as I understand the [https://github.com/jgitver/jgitver-maven-plugin](jgitver-maven-plugin) allows configuration for `regexVersionTag` (and others). If this gradle plugin would support this too, I would be helped. (I assume that this is gradle plugin is equivalent to the magen-plugin)

**Comment by McFoggy** [comment]
@yo1-markenstein I'll publish this WE a version wich exposes most (if not all) possible existing configurations.
If you are able to write a single regexp matching all your version pattern the it will do the trick.

**Comment by yo1-markenstein** [comment]
Wow, great. Appreciate this prompt service.
Have a nice weekend then ;-)

**Comment by McFoggy** [comment]
@yo1-markenstein `0.3.2` is out and published. 

I have added also some [_Integration tests_](https://github.com/jgitver/gradle-jgitver-plugin#integration-tests) to ease testing features, I pushed an example that sets `regexVersionTag`.

**Comment by yo1-markenstein** [comment]
Hi Matthieu,

Just to let you know: Thanks for the new version. I does bring me what I
needed.
I have to dig up my regular expression skills as my initial modification
resulted in a nasty stacktrace (although https://regexr.com/ validated my
proposed string), but I found one that works.
We are still evaluating your plugin and it is still promising. Since this
setup requires consciously manipulating git tags I am working out some more
aid / automation when starting a branch and accepting pull-requests
(=release in our case).

Oh and am not much a blogger, sorry ;-)

Cheers,

Johan


2017-11-25 12:22 GMT+01:00 Matthieu Brouillard <notifications@github.com>:

**Comment by McFoggy** [comment]
Thanks for the feedback Johan.

> Since this setup requires consciously manipulating git tags
> I am working out some more aid / automation when starting a branch and accepting pull-requests

If possible, once you're done, I think it would be valuable to explain afterwards your setup. We can create some wiki entries for _testimonials_.

> ... accepting pull-requests ...

In CI scenarios building specific versions from PR might be easy with jgitver (it was created for handling such cases). And it is especially true if you correctly control the build behind webhooks receiving github/gitlab/bitbucket notifications. 

Please keep me up to date with what you ended up and do not hesitate to come back to me, to open issues or to use the gitter [room](https://gitter.im/jgitver/Lobby).
